version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.walletdocs.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.walletdocs.entrypoints=web"
      - "traefik.docker.network=proxy"
    networks:
      proxy:
        ipv4_address: 10.200.3.1

networks:
  proxy:
    external: true
